// ==========================================
// 重返2008：梦境碎片 - 游戏配置（完整剧本版 v3）
// ==========================================

const GAME_CONFIG = {
    version: '3.0.0',
    dreamDate: '2008年6月21日',
    dreamDay: '星期六',

    protagonist: {
        name: '林瑜',
        age2026: 26,
        age2008: 8,
        job: '互联网公司运营专员',
        city: '上海',
        hometown: '南昌',
    },

    scenes: {
        prologue: {
            id: 'prologue', name: '序章', year: 2008,
            title: '苏醒与错位',
            subtitle: '天花板上那道裂纹还在……这不是2026年的卧室。',
            className: 'warm-shift',
            bgImage: 'images/bg_prologue.jpg',
        },
        chapter1: {
            id: 'chapter1', name: '第一章', year: 2008,
            title: '熟悉的陌生房间',
            subtitle: '客厅的每一件东西都在，但好像隔着什么。',
            className: 'warm-shift vhs-effect',
            bgImage: 'images/bg_chapter1.jpg',
        },
        chapter2: {
            id: 'chapter2', name: '第二章', year: 2008,
            title: '永远走不出的街道',
            subtitle: '阳光刺眼，街道没有尽头，但你想走完它。',
            className: 'warm-shift vhs-effect',
            bgImage: 'images/bg_chapter2.jpg',
        },
        chapter3: {
            id: 'chapter3', name: '第三章', year: 2008,
            title: '游乐场的幻梦',
            subtitle: '旋转木马在空转。秋千在无风中自己晃动。',
            className: 'warm-shift',
            bgImage: 'images/bg_chapter3.jpg',
        },
        epilogue: {
            id: 'epilogue', name: '终章', year: 2026,
            title: '回归与释怀',
            subtitle: '窗外阳光明媚。她决定今天去买一盒水彩。',
            className: 'cool-shift',
            bgImage: 'images/bg_epilogue.jpg',
        },
    },
};

// ===== 场景完整数据 =====
const SCENE_DATA = {

    prologue: {
        objects: [
            { id: 'ceiling_crack', name: '天花板裂纹', x: 50, y: 10, width: 90, height: 45,
              description: '从灯座延伸到墙角的天花板裂纹，像一条干涸的河床。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '这道裂纹——我小时候就盯着它发呆。没想到2026年的公寓天花板上也有同样的裂纹。是同一栋楼吗？还是所有老房子的天花板都是一样的？' } },
            { id: 'fan', name: '老式吊扇', x: 50, y: 16, width: 80, height: 55,
              description: '吊扇吱呀吱呀地转着，拉绳上系着红毛线。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '拉绳太短了，小时候够不着，我自己系了一根红毛线上去。十几年了，这根毛线还在。它像是这个房间里唯一没有变旧的东西。' } },
            { id: 'window', name: '蓝色玻璃窗', x: 22, y: 32, width: 75, height: 95,
              description: '窗外有蝉鸣。蓝色玻璃把阳光染成了不真实的颜色。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '那个年代家家户户都装这种蓝色玻璃。阳光透进来就变成蓝色的，像水底的光。后来这种玻璃被淘汰了。我也是去了上海之后才知道，大多数地方的夏天——不是蓝色的。' } },
            { id: 'homework', name: '暑假作业', x: 28, y: 58, width: 65, height: 50,
              description: '二年级暑假作业，铅笔字只写了一页。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '"小明有5个苹果，小红有3个苹果……"我在这道题前面坐了一个下午。一个字都没写——因为楼下周小萌在喊我出去玩。那时候觉得暑假作业好多。现在只想回去写作业。' },
              isMemory: true, memoryName: '暑假作业本' },
            { id: 'desk', name: '书桌', x: 28, y: 52, width: 85, height: 65,
              description: '老式木质书桌，桌角磨掉了漆。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '抽屉里还有我藏的贴纸——不干胶的那种，几块钱一大张。那时候觉得这是世界上最珍贵的财富。现在一张都舍不得撕。' } },
            { id: 'bed', name: '竹席床', x: 72, y: 52, width: 85, height: 65,
              description: '竹凉席已经睡出了一个人形的印子。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '竹席的味道。夏天的味道。妈妈每年夏天都会用湿毛巾擦一遍竹席，然后放在通风处晾干。我在上海睡的是空调房，已经很多年没有闻到过竹席的味道了。' } },
            { id: 'exit_prologue', name: '推开卧室门 →', x: 50, y: 88, width: 100, height: 38,
              description: '卧室门半掩着，外面有光透进来。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '我走到门前。推开门。客厅的光线涌进来——浓烈的、令人昏昏欲睡的午后阳光。我该出去看看。' },
              isExit: true },
        ],
        introMonologue: '你睁开眼。\n天花板上那道裂纹从灯座延伸到墙角。\n窗外传来蝉鸣。\n风扇在转。\n……这不是你在上海租的那个房间。',
    },

    chapter1: {
        sunRays: true,
        objects: [
            { id: 'tv', name: '大屁股电视', x: 42, y: 36, width: 95, height: 75,
              description: '一台老式CRT电视，上面盖着蕾丝防尘布。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '电视上面盖着蕾丝布。遥控器用塑料袋包着。VCD机里有一张《七里香》——那是小姑从深圳带回来的正版碟。那时候觉得家里有一台VCD机是很了不起的事。' },
              isMemory: true, memoryName: '老电视和VCD' },
            { id: 'note', name: '妈妈的字条', x: 58, y: 58, width: 58, height: 48,
              description: '一张红线信纸，用五块钱压着。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '"饭菜在锅里，记得吃。零花钱在抽屉里。妈妈晚上七点回来。" 字条旁边放着五块钱——崭新的、2005年版的。我拿起那张钱。它还很新，没有折痕。就像妈妈刚去银行换回来的一样。' },
              isKey: true, memoryName: '妈妈的字条和五块钱' },
            { id: 'photo', name: '全家福', x: 22, y: 28, width: 58, height: 68,
              description: '茶几玻璃下压着一张2006年的全家福。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '爸爸穿着皮夹克，妈妈烫着卷发。我坐在中间，门牙少了一颗，笑得眼睛眯成一条线。那时候爸爸还没有白头发，妈妈的腰也好好的。我以为他们会一直这么年轻。' },
              isMemory: true, memoryName: '2006年的全家福' },
            { id: 'phone', name: '座机电话', x: 78, y: 38, width: 48, height: 58,
              description: '老式座机。屏幕显示：2008-06-21 14:17',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '2008年6月21日，星期六，下午两点十七分。如果这个时间是真的——那离我从上海那张床上醒来，还不到半个小时。但我感觉已经在这里待了一整个夏天了。' },
              isTrigger: true },
            { id: 'mom_voice', name: '妈妈的声音', x: 65, y: 22, width: 50, height: 45,
              description: '从厨房传来锅铲翻炒的声音……但厨房里没有人。',
              onClick: 'npc', dialogueTree: 'mom_voice', isNPC: true },
            { id: 'xiaomeng', name: '周小萌', x: 85, y: 72, width: 52, height: 72,
              description: '扎着双马尾的女孩在楼下朝你挥手。',
              onClick: 'npc', dialogueTree: 'xiaomeng', isNPC: true },
            { id: 'exit_chapter1', name: '下楼出门 →', x: 50, y: 90, width: 100, height: 38,
              description: '楼梯通往楼下。周小萌在喊你出去玩。',
              onClick: 'dialog', dialog: { speaker: '周小萌', text: '（从楼下传来）林——瑜——！你怎么还没好啊！太阳都要下山啦！今天去不去小卖部？' },
              isExit: true },
        ],
        introMonologue: '客厅的茶几上放着那台大屁股电视。\n蕾丝布。VCD机。全家福。\n电话的屏幕亮着：2008年6月21日，星期六。\n你站在客厅中间。楼上传来电视声。',
    },

    chapter2: {
        sunRays: true,
        objects: [
            { id: 'granny_wang', name: '王奶奶', x: 18, y: 52, width: 58, height: 78,
              description: '穿着碎花衬衫，手里拿着蒲扇，坐在门口择菜。',
              onClick: 'npc', dialogueTree: 'wang_granny', isNPC: true },
            { id: 'xiaomeng', name: '周小萌', x: 38, y: 58, width: 52, height: 72,
              description: '你的童年最好的朋友，永远八岁。',
              onClick: 'npc', dialogueTree: 'xiaomeng', isNPC: true },
            { id: 'store', name: '小卖部', x: 68, y: 48, width: 78, height: 68,
              description: '校门口的小卖部。冰柜里摆着老冰棍和绿舌头。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '陈叔的小卖部。五毛一包的辣条、一毛一颗的西瓜糖、还有那种刮奖卡——陈叔会在你中了五毛的时候笑着说「今天运气不错」。' } },
            { id: 'shop_owner', name: '陈叔', x: 72, y: 55, width: 55, height: 72,
              description: '小卖部老板，戴着老花镜，手指夹着一根烟。',
              onClick: 'npc', dialogueTree: 'shop_owner', isNPC: true },
            { id: 'school_gate', name: '学校大门', x: 28, y: 62, width: 52, height: 85,
              description: '铁门锁着。透过栅栏能看到操场——草长得很高了。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '今天是星期六，学校没人。以前总是在这里等小萌一起回家。2008年10月她搬去了深圳——我们写过信，后来断了。我再也没有见过她。在我的记忆里，她永远八岁。' },
              isMemory: true, memoryName: '周小萌的约定' },
            { id: 'teacher_li', name: '李老师', x: 32, y: 48, width: 50, height: 75,
              description: '穿着白衬衫的班主任，手表停在下午三点五十分。',
              onClick: 'npc', dialogueTree: 'teacher_li', isNPC: true },
            { id: 'bicycle', name: '二八大杠', x: 52, y: 68, width: 78, height: 55,
              description: '一辆老式自行车靠在墙边，车漆掉了不少。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '爸爸的自行车。小时候上学、出去玩、去外婆家……都是坐这辆车。前座横梁是我的专属座位。冬天爸爸会脱了外套把我裹住，他的背又宽又暖。好多年没有坐过自行车后座了。' } },
            { id: 'flower_wall', name: '蔷薇花墙', x: 88, y: 42, width: 68, height: 78,
              description: '学校后墙开满了红色的蔷薇花，在正午阳光下发亮。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '这面花墙。我和小萌的秘密基地。我们从左边数第三棵蔷薇下面埋过一颗玻璃弹珠——用一个铁皮饼干盒子装着。说好了二十年后再来挖。二十年到了。我还记得。' },
              isMemory: true, memoryName: '蔷薇花下的约定' },
            { id: 'exit_chapter2', name: '走向游乐场 →', x: 55, y: 88, width: 82, height: 38,
              description: '街角转弯处，通往游乐场的方向。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '顺着这条街往前走，就是游乐场了。我的腿比我的脑子更知道要去哪里。' },
              isExit: true },
        ],
        introMonologue: '阳光刺眼。\n小区里没有一个人。那条走了无数遍的上学路——\n好像变窄了，又好像没变。\n你走上街道。蝉鸣铺天盖地。',
    },

    chapter3: {
        sunRays: true,
        objects: [
            { id: 'carousel', name: '旋转木马', x: 38, y: 32, width: 120, height: 95,
              description: '漆面已斑驳。彩色灯泡还挂着。没有音乐。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '旋转木马不转了。但你看它的时候——它好像动了一下。就像在等你。' },
              isKey: true, memoryName: '旋转木马' },
            { id: 'elephant_slide', name: '大象滑梯', x: 22, y: 52, width: 88, height: 78,
              description: '灰色水泥大象，鼻子磨得光滑发亮。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '小时候它好大——大象的耳朵到我下巴。现在蹲下来，它只到我腰间。不是它变小了。是我变远了。' },
              isMemory: true, memoryName: '大象滑梯' },
            { id: 'ball_pool', name: '海洋球池', x: 68, y: 52, width: 78, height: 68,
              description: '彩球大半已瘪，池底有一层灰。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '我掉进去过一次。五岁。池子太深了，我爬不出来，急得直哭。爸爸笑着把我捞出来，举得高高的：「下次不许了。」但我还是偷偷去。因为那些彩色的球——太漂亮了。' } },
            { id: 'marble', name: '玻璃弹珠', x: 48, y: 62, width: 42, height: 42,
              description: '池底捡到的透明弹珠，里面有蓝色花瓣。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '一颗弹珠。里面有一片蓝色的花瓣。和小萌埋在学校后墙的那颗一模一样。但我口袋里的那颗还在。那这颗是谁的？它在等我吗？' },
              isKey: true, memoryName: '玻璃弹珠' },
            { id: 'coin_ride', name: '小熊摇摇车', x: 55, y: 40, width: 58, height: 68,
              description: '投币的小熊摇摇车，漆面褪成了粉白色。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '我投了五毛钱——就是妈妈留下来那张。摇摇车动了一下，然后走调的《小星星》响了起来。声音在空旷的游乐场里回响了很久。' },
              isMemory: true, memoryName: '摇摇车与小星星' },
            { id: 'mysterious_boy', name: '秋千上的男孩', x: 80, y: 38, width: 58, height: 72,
              description: '一个穿着和你一样校服的男孩坐在秋千上。他的脸是模糊的。',
              onClick: 'npc', dialogueTree: 'mysterious_boy', isNPC: true },
            { id: 'exit_chapter3', name: '黄昏·该回家了 →', x: 50, y: 90, width: 100, height: 38,
              description: '天色暗下来了。你知道该回去了。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '天色暗下来了。游乐场安静得像一幅画。你闭上眼睛。数到三。回到2026年。' },
              isExit: true },
        ],
        introMonologue: '游乐场和记忆中一模一样。\n只是安静得不像真的。\n旋转木马不转了。\n但你总觉得——它们在等你来。',
    },

    epilogue: {
        objects: [
            { id: 'sunlight', name: '窗外的光', x: 50, y: 28, width: 95, height: 85,
              description: '清晨的阳光穿过窗帘，带着金色的暖意。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '我回来了。天花板上那道裂纹还在。但它看起来——不像干涸的河床了。像一条路。从过去通向现在的路。' },
              isKey: true },
            { id: 'marble_keepsake', name: '口袋里的弹珠', x: 32, y: 68, width: 48, height: 48,
              description: '口袋里有一颗透明弹珠。还有一张折得整整齐齐的五块钱。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '它们跟我回来了。我把它放在床头柜上。阳光照进来的时候，蓝色花瓣会闪光。' },
              isMemory: true, memoryName: '2008年的信物' },
            { id: 'phone_2026', name: '手机', x: 68, y: 72, width: 38, height: 58,
              description: '屏幕亮着——7:15。闹钟还有十五分钟。',
              onClick: 'dialog', dialog: { speaker: '林瑜', text: '今天是星期天。不用上班。冰箱里有番茄和鸡蛋。我决定今天去买一个西瓜。再买一盒水彩。' },
              isEnding: true },
        ],
        introMonologue: '你睁开眼睛。\n天花板上的裂纹还在。\n但你躺在2026年的床上。\n……有什么东西在口袋里。\n你把它拿出来——是一颗弹珠。\n还有一张五块钱。',
    },
};
